name: resistor_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  bloc: ^8.1.2
  equatable: ^2.0.5
  firebase_core: ^2.21.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^6.3.2
  go_router: ^11.0.0
  google_fonts: ^6.1.0
  intl: ^0.18.1
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.4

flutter:
  generate: true
  uses-material-design: true
